[build]
  command = "npm install -D @stackbit/types @stackbit/cms-git && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.2" # Match your Gemfile
  JEKYLL_ENV = "production"
