backend:
  name: git-gateway
  branch: main  # Your default Git branch
media_folder: "images/uploads"  # Where uploaded images go
collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"  # Jekyll posts folder
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Content", widget: "markdown" }
