name: Sync Preview with Master
on:
  push:
    branches: [ master ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Force Sync Preview Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin master preview
          git checkout preview
          git reset --hard origin/master  # Completely overwrite preview
          git push origin preview --force
